export const categories = [
    { category: "Beachfront" },
    { category: "icons" },
    { category: "islands" },
    { category: "Arctic" },
    { category: "Earth homes" },
    { category: "castle" },
    { category: "historical homes" },
    { category: "Cabins" },
    { category: "Houseboats" },
    { category: "Amazing views" },
    { category: "Bed & breakfasts" },
    { category: "Amazing pools" },
    { category: "Top cities" },
    { category: "Countryside" },
    { category: "National parks" },
    { category: "Campers" },
    { category: "OMG" },
    { category: "Design" },
    { category: "Beach" },
    { category: "Trending" },
    { category: "Surfing" },
    { category: "Rooms" },
    { category: "Caves" },
    { category: "Tropical" },
    { category: "New" },
    { category: "Lake" },
    { category: "Mansions" },
    { category: "Camping" },
    { category: "A-Frames" },
    { category: "Luxe" },
    { category: "Golfing" },
    { category: "Tiny homes" },
    { category: "Vineyards" },
    { category: "Top of the world" },
    { category: "Skiing" },
    { category: "Hanoks" },
    { category: "Windmills" },
    { category: "Farms" },
    { category: "Cycladic homes" },
    { category: "Chef's kitchens" },
    { category: "Lakefronts" },
    { category: "Shepherd's huts" },
    { category: "Treehouses" },
    { category: "Casas particulares" },
    { category: "Barns" },
    { category: "Ryokans" },
    { category: "Desert" },
    { category: "Minsus" },
    { category: "Domes" },
    { category: "Towers" },
    { category: "Yurts" },
    { category: "Adapted" },
    { category: "Ski-in/out" },
    { category: "Off-the-grid" },
    { category: "Play" },
    { category: "Boats" },
    { category: "Containers" },
    { category: "Creative spaces" },
    { category: "Grand pianos" },
    { category: "Riads" },
    { category: "Dammusi" },
    { category: "Trulli" },
  ];